{
    "name": "Rias-Gremory",
    "version": "3.0.0",
    "description": "WhatsApp  Bot Using Nodejs",
    "main": "index.js",
    "type": "commonjs",
    "directories": {
        "commands": "commands",
        "database": "database",
        "session": "session", 
        "Toxxic": "Toxxic", 
        "tmp": "tmp"
    },
    "scripts": {
        "start": "node index.js"
    },
    "author": "Toxxic",
    "license": "MIT",
    "dependencies": {
        "@whiskeysockets/baileys": "^6.7.9",
        "@adiwajshing/keyed-db": "^0.2.4",
        "@hapi/boom": "^10.0.1",
        "awesome-phonenumber": "^7.2.0",
        "axios": "^1.7.7",
        "chalk": "^4.1.2",
        "wa-sticker-formatter": "^4.4.4",
        "cheerio": "^1.0.0-rc.12",
        "cookie": "^0.5.0",
        "dotenv": "^16.0.1", 
        "express": "^4.21.1", 
        "file-type": "^16.5.3",
        "fluent-ffmpeg": "^2.1.2",
        "form-data": "^4.0.0",
        "fs-extra": "^11.1.1",
        "https": "^1.0.0", 
        "human-readable": "^0.2.1",
        "jimp": "^0.16.1",
        "jsdom": "^25.0.1",
        "javascript-obfuscator": "^4.1.1",
        "mathjs": "^13.2.2",
        "moment-timezone": "^0.5.46",
        "node-fetch": "^2.6.11",
        "node-cache": "^5.1.2", 
        "performance-now": "^2.1.0",
        "pino": "^9.5.0", 
        "vm": "^0.1.0", 
        "simple-git": "^3.27.0", 
        "yt-search": "^2.12.1"
    }
}
